<div id="tbl_forms" style="width:100%"></div>
<br />
<input id="btn_add_form" type="button" value="Add Form" />
<div id="div_modify">
	<form id="form_form" method="post" enctype="multipart/form-data" action="<?php echo $this->_config->url->upload ?>intranet/forms/">
		<input type="hidden" id="obj_uid" name="obj_uid" value="" />
		<h4>Add / Modify Form</h4>
		<table class="mng">
			<tr>
				<td>Name:</td>
				<td><input name="obj_name" id="obj_name" /></td>
				<td class="eg">(eg: Personal Data Form)</td>
			</tr>
			<tr>
				<td>Department:</td>
				<td><input name="obj_department" id="obj_department" /></td>
				<td class="eg">(eg: Payroll)</td>
			</tr>
			<tr>
				<td>FileType:</td>
				<td><input name="obj_filetype" id="obj_filetype" /></td>
				<td class="eg">(eg: pdf, gif, xls, doc, link)</td>
			</tr>
			<tr>
				<td>File:</td>				
								<!--BEGIN - Tecnics 20190604 Created Dummy Object Tag to fix flash issue in Edge browser-->
							    <!-- <object width="0" height="0" data="/f/uploadify.swf" type="application/x-shockwave-flash"></object> -->

								<!--END - Tecnics 20190604 Created Dummy Object Tag to fix flash issue in Edge browser-->
				
				<td><input id="obj_files" name="obj_file" type="file" />
				<!-- <div id="fileQueue" style="text-align:left"></div><a href="javascript:$('#obj_files').uploadifyClearQueue();">Clear Queue</a> -->
				<div id="fileQueue" style="text-align:left"></div><a href="#" id="clear_queue">Clear Queue</a>
			    </td>
				<td class="eg">(Leave blank if not changing file)</td>
			</tr>
			<tr>
				<td></td>
				<td><input type="submit" name="obj_submit" id="obj_submit" value="Submit" /></td>
				<td class="eg"></td>
			</tr>
		</table>
	</form>
</div>
<div id="div_indicator" class="indicator"></div>
<script type="text/javascript">
	_controller = {
		 baseview: 'forms'
		,session: '<?php echo $this->acl->Request()->Session->SessionID; ?>'
		,cookie: '<?php echo $this->acl->User()->uid; ?>'
		,uploadify: {
			 sizelimit: '<?php echo $this->_config->forms->sizelimit; ?>'
			,uancDomain: '<?php echo $this->_config->uploadify->uancDomain ?>'
		}
	};
</script>
<script type="text/javascript">
	$(document).ready(function(){
		$("#div_modify").hide();
		$("#div_indicator").hide();
		$("#btn_add_form").click(function(){$("#div_modify").trigger("addform");});
		$("#tbl_forms").CrayView({
			 baseview: _controller.baseview
			,session: _controller.session
			,cookie: _controller.cookie
			,cdb: 'config:newparkinfo'
			,url: '/view'
			,theme: 'slick'
			,rowHover: true
			,rowClick: function(data){
				$("#div_modify").trigger("editform", data.UID);
			}
			,style: {
				 div_container: {css:{width:'100%','font-size':'11px','font-family':'Verdana, "Segoe UI", Tahoma, Arial',overflow:'auto'}}
//				,div_pag: {div_display:{html:{singular:'{end} of {count}',plural:'{begin} - {end} of {count}'}}}
//				,table: {css:{width:'100%'}}
			}
			,api: {
				 onBeforeBuild: function(data){
					data.properties.struct.col.push({
						 AUF: false
						,Data: false
						,Hide: false
						,Name: "Delete"
						,Order:99
						,Sortable:false
						,Type:"TEXT"
						,UID:"12345678-1234-4321-0123-012345678901"
					});
				}
				,onBeforeAddRow: function(data,target,iteration){
					//delete
					data.Delete = '<a href="#"><img src="/i/delete.png" border="0" /></a>';

					data["Date Modified"] = data["Date Modified"].replace(/ ?[0-9]{2}\:[0-9]{2}\:[0-9]{2,}/i, '');
					data["Type"] = '<img src="http://upload.apps.newpark.com/i/type/icon_'+data["Type"]+'.png" />';
				}
				,onAfterAddRow: function(data,target) {
					target.children("td:last-child").children("a:eq(0)").click(function(e){
						e.stopPropagation();
						if (confirm("Are you sure you want to delete this form?"))
							$.getJSON('/forms/manage', {action: 'deleteform',formid:data.UID},function(cdata){try{$("#tbl_forms").CrayView("api").refresh();}catch(e){}});
					});
				}
			}
		});

		$("#div_modify")
			.hide()
			.bind("addform", function(event){
				try{$('#obj_file').uploadifyClearQueue();}catch(e){}
				$(this).show();
//				if ($("#obj_uid").val().length > 0)
//				{
					$(this).find("input[type=text]").val("");
//				}
				$("#obj_uid").val("");
			})
			.bind("editform", function(event, uid){
				try{$('#obj_file').uploadifyClearQueue();}catch(e){}
				var $this = $(this);
				$(this).hide();
				$("#div_indicator").show();
				$("#obj_uid").val(uid);
				$.getJSON('/forms/manage', {action: 'getform', formid: uid}, function(data){
					$("#div_indicator").hide();
					if (data.status != "success")
						alert(data.errors.err[0]);
					else
					{
						var d = data.properties.data;
						$this.show();
						$("#obj_name").val(d.n);
						$("#obj_department").val(d.d);
						$("#obj_filetype").val(d.t);
					}
				})
			})
			;
		$("#form_form")
			.submit(function(){
				if ($("#obj_name").val().length <= 0)
				{
					alert("Please enter a name");
					return false;
				}

				if ($("#obj_name").val().length > 255)
				{
					alert("Name can not be greater than 255 characters");
					return false;
				}

				if ($("#obj_department").val().length <= 0)
				{
					alert("Please enter a department");
					return false;
				}

				if ($("#obj_department").val().length > 255)
				{
					alert("Department can not be greater than 255 characters");
					return false;
				}

				if ($("#obj_filetype").val().length <= 0)
				{
					alert("Please enter a filetype");
					return false;
				}

				if ($("#obj_filetype").val().length > 50)
				{
					alert("Filetype can not be greater than 50 characters");
					return false;
				}

				if ($("#obj_uid").val().length <= 0 && !$("#obj_files").data("queuedFile"))
				{
					alert("While adding a form, you must select a file.");
					return false;
				}

				$("#div_indicator").show();

				if ($("#obj_files").data("queuedFile"))
					$("#obj_files").uploadifyUpload();
				else
					$(this).trigger("realSubmit");
				return false;
			})
			.bind("realSubmit", function(event, formfilename, formfilesize, formfilecontenttype){
				$.getJSON('/forms/manage', {
						 action:'modifyform'
						,formid:$("#obj_uid").val()
						,formname:$("#obj_name").val()
						,formdept:$("#obj_department").val()
						,formtype:$("#obj_filetype").val()
						,formfilename:formfilename
						,formfilesize:formfilesize
						,formfilecontenttype:formfilecontenttype
					}
					,function(cdata){
						try{$("#tbl_forms").CrayView("api").refresh();}catch(e){}
						if (cdata.status=="success")
						{
							$("#obj_uid").val("");
							$("#div_modify").trigger("addform");
						}
					}
				);
				$("#div_indicator").hide();
			})
			;
	});

	$('#clear_queue').click(function() {
		$('#obj_files').val('');
	});

	//uploadify
	$(document).ready(function() {
		$("#obj_files").data("queuedFile", false);
		
		$("#obj_file").uploadify({
			 'uploader'       : '/f/uploadify.swf'
			,'script'         : 'http://'+_controller.uploadify.uancDomain+'/intranet/forms'
			,'cancelImg'      : 'http://'+_controller.uploadify.uancDomain+'/i/cancel.png'
//			,'buttonImg'      : 'http://'+_controller.uploadify.uancDomain+'/i/cts/browse-files.png'
			,'folder'         : 'forms'
			,'wmode'          : 'transparent'
			,'width'          : 96
			,'queueID'        : 'fileQueue'
			,'auto'           : false
			,'multi'          : false
			,'scriptAccess':'always'
			,'sizeLimit':_controller.uploadify.sizelimit
			,onSelectOnce: function (event, data) {
				$(this).data("queuedFile", true);
			}
			,onCancel:function(){
				$("#obj_files").data("queuedFile", false);
			}
			,onClearQueue:function(){
				$(this).data("queuedFile", false);
			}
			,onError: function(){
				$("#div_indicator").hide();
			}
			,onComplete: function(event, queueID, fileObj, response, data){
				response = $.parseJSON(response);
				//alert(response.properties.msg);
				if (response.status == "success")
				{
					var file = response.properties.files[0];
					$("#form_form").trigger("realSubmit", [file.name, file.size, file.type]);
				} else
					$("#div_indicator").hide();
			}
			,onAllComplete: function(event, queueID, fileObj, response, data){
				$("#obj_files").data("queuedFile", false);
				$(this).uploadifyClearQueue();
			}
		});
	});
</script>